POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Rest test",
    "author": "Rester the Tester",
    "url": "https://example.com/",
    "likes": 0
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "tester",
    "name": "Test Tester",
    "password": "sekret"
}